### ISSUE TITLE
Have support in multiple channels

### ISSUE THREAD

**Issue by sonbua** [sonbua/InMemoryMessageBus#1]
1. Each message published to the bus should have the channel name specified beforehand. If no channel was specified, this message will end up in the default channel. Maybe `_default_channel` is a good default.
2. Each subscriber subscribed to the bus should have the channel name specified. If no channel was specified, this subscriber will subscribe to the default channel.

**Comment by badpaybad** [comment]
In my opinion default_channel may no need, It will cause of confuse. Each channel should handle one type of data, each channel handle one business, actually one function to process data , eg: single responsibility principle . 
Instead of default channel , could be throw exception.

**Comment by sonbua** [comment]
Agree. A typical setup would look like this:
```c#
// Subscription
bus.Subscribe(
    subscriber: new Subscriber("a subscriber", message => { /* Consume the message */ })
    channel: "channel-name");

// Publishing
bus.Publish("a message", "channel-name");
```

For a small application, which uses a single channel, the name could be discarded for convenience. In this case, the channel defaults to `_default_channel`, which might also be configurable.
```c#
// Subscription
bus.Subscribe(new Subscriber("a subscriber", message => { /* Consume the message */ }));

// Publishing
bus.Publish("a message");
```

**Comment by sonbua** [comment]
@badpaybad
Would you mind reviewing the above PR?
